image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Set Kubernetes Contexts
    command: echo $K8S_CTX | base64 -d > ~/.kube/config
  - init: cd server; npm install
  - init: cd app; npm install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6379
    onOpen: ignore
  - port: 6380
    onOpen: ignore
  - port: 3000
    onOpen: notify
  - port: 4200
    onOpen: open-browser
