stages:
  - build
  - release

.dagger:
  image: grahamhub/joyeuse-dagger:latest
  variables:
    DAGGER_LOG_FORMAT: plain
    DAGGER_LOG_LEVEL: info
    DAGGER_CACHE_PATH: .dagger-cache
  services:
    - docker:dind
  before_script:
    - cp -R /tmp/cue.mod /builds/joyeuse-app/joyeuse
  cache:
    key: dagger-${CI_JOB_NAME}
    paths:
      - ${DAGGER_CACHE_PATH}

docker-build:
  extends: [.dagger]
  stage: build
  script:
    - echo $(pwd)
    - echo $(find / -type d -name 'cue.mod')
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
        dagger do \
          --cache-from type=local,src=${DAGGER_CACHE_PATH} \
          --cache-to type=local,mode=max,dest=${DAGGER_CACHE_PATH} \
          pushFromMain
      else
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $CI_COMMIT_REF_SLUG"
        dagger do \
          --cache-from type=local,src=${DAGGER_CACHE_PATH} \
          --cache-to type=local,mode=max,dest=${DAGGER_CACHE_PATH} \
          pushFromCommit
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

docker-release:
  extends: [.dagger]
  stage: release
  script:
    - |
      dagger do \
        --cache-from type=local,src=${DAGGER_CACHE_PATH} \
        --cache-to type=local,mode=max,dest=${DAGGER_CACHE_PATH} \
        release
  rules:
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile
