FROM docker:latest as dagger

RUN apk add --no-cache curl

WORKDIR /usr/local
RUN curl -L https://dl.dagger.io/dagger/install.sh | sh

FROM docker:latest as deps

COPY cue.mod cue.mod
COPY --from=dagger /usr/local/bin/dagger /usr/local/bin/dagger
RUN dagger project update

FROM docker:latest

COPY --from=deps cue.mod /builds/joyeuse-app/joyeuse/cue.mod
COPY --from=dagger /usr/local/bin/dagger /usr/local/bin/dagger