apiVersion: v2
name: joyeuse
description: A Helm chart for Kubernetes for The Speaker Discord bot
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.4.5
    condition: redis.enabled