---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-credentials
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ include "joyeuse.imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson