apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-speaker
spec:
  replicas: {{ .Values.speaker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: the-speaker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: the-speaker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configs/speaker-config.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: speaker-config
          configMap:
            name: speaker-config
      containers:
        - name: {{ .Chart.Name }}
          image: jeddai/the-speaker:{{ .Values.speaker.version }}
          imagePullPolicy: Always
          env:
            - name: CONFIG_PATH
              value: /app/config.yaml
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-secret
                  key: token
          volumeMounts:
            - name: speaker-config
              mountPath: /app/config.yaml
              subPath: config.yaml
